---
title: "Exploratory analysis"
author: "Eva Sahlholdt Hansen and Matilde Jacobsen"
date: "5/19/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r loading data}
pacman::p_load(tidyverse, 
               brms,
               bayesplot,
               viridis,#color pallette
               stringr,
               lme4,
               lmerTest, 
               rstatix,
               tidybayes,
               wesanderson, #color pallette
)

d <- sc_df_clean <- read_csv("sc_df_clean.csv")
demo <- read_csv("Demographic responses.csv")

```

Type of feedback: low, medium, high
```{r }
#Creating different subsets for different types of feedback and new column for for 3 levels of feedback
dLow <- subset(d, Feedback %in% c(-1,1,0))
dLow$FeedbackType <- "low"
dMedium <- subset(d, Feedback %in% c(2,-2))
dMedium$FeedbackType <- "medium"
dHigh <- subset(d, Feedback %in% c(3,-3))
dHigh$FeedbackType <- "high"

d <- rbind(dLow,dMedium,dHigh)
```

Anticonform: negative feedback & positive change, postitive feedback & negative change
```{r}
dAntiN <- subset(d, Feedback < 0 & Change > 0)
dAntiN$Anti <- "negative_feedback"
dAntiP <- subset(d, Feedback > 0 & Change < 0)
dAntiP$Anti <- "positive_feedback"

dAnti <- rbind(dAntiN,dAntiP)
d2 <- d - dAnti
d$AntiConform <- d %>%  transmute(
  ifelse(Feedback < 0 & Change > 0, "negative",
                         ifelse(Feedback > 0 & Change < 0, "positive",
                                ifelse(FirstRating == SecondRating, "no_effect", "conform")))
)


```

Modelling participants by waiting period for own study
```{r}
time <- read.csv("time.csv")
df <- read.csv("Raw data/d38.csv")
df_time <- merge(time, df, by = "ID")

WaitConformity_f1 <- bf(Change ~ 1 + FirstRating + Feedback + 
                         (1 + FirstRating + Feedback + hours | ID) + 
                         (1 + FirstRating + Feedback | FaceID))

get_prior(WaitConformity_f1, df_time, family = gaussian)

WaitConformity_prior <- c(
  prior(normal(0, 1), class = Intercept),
  prior(normal(0, .3), class = b),
  prior(normal(0, .3), class = sd),
  prior(lkj(5), class = cor),
  prior(normal(0,1), class = sigma)
)

WaitConformity_m_prior <- brm(
  WaitConformity_f1,
  df_time,
  family = gaussian,
  prior = WaitConformity_prior,
  sample_prior = "only",
  chains = 2,
  cores = 2,
  control = list(
    adapt_delta = 0.99,
    max_treedepth = 20
  )
)

prior_check <- pp_check(WaitConformity_m_prior, nsamples=100)

(prior_check
  +ggtitle("Prior predictive check"))

WaitConformity_m <- brm(
  WaitConformity_f1,
  df_time,
  family = gaussian,
  prior = WaitConformity_prior,
  sample_prior = T,
  chains = 4,
  cores = 2,
  iter = 4000,
  control = list(
    adapt_delta = 0.99,
    max_treedepth = 20
  )
)
post_check <- pp_check(WaitConformity_m, nsamples=100)
summary(WaitConformity_m)
round(posterior_summary(WaitConformity_m, pars = c("^b_", "^sd_","^cor_"), probs = c(0.025, 0.975) ),3)
```

Exploratory regression of waiting time
```{r}
cogsci_clean <- read_csv("cogsci_clean.csv")


```

